# Site settings
title: Raphael Lehmann
email: kontakt@rleh.de

description: > # this means to ignore newlines until "baseurl:"
  Webseite von Raphael Lehmann. Infos Ã¼ber mich, mein Studium und Projekte.
baseurl: ""
url: "https://www.rleh.de"

github_username:  rleh

# Build settings
#markdown: kramdown
markdown: redcarpet